packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  bufferutil: true
  core-js: true
  esbuild: true
  unrs-resolver: true
  utf-8-validate: true

# allowBuilds:
# esbuild: set this to true or false
