import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppProviders } from "@/providers/AppProviders";
import { HeaderNav } from "@/components/header-nav/HeaderNav";
import { FooterNav } from "@/components/footer-nav/FooterNav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex justify-between flex-col">
        <AppProviders>
          <HeaderNav />
          <main className="flex-1 h-full flex flex-col justify-center items-center">
            {children}
          </main>
          <FooterNav />
        </AppProviders>
      </body>
    </html>
  );
}
